### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by vmachacek** [cschleiden/github-actions-hero#10]
both of those urls are showing An unexpected error has occurred.

https://github-actions-hero.now.sh/playground
https://github-actions-hero.now.sh/lessons/1

**Comment by Gothicania** [comment]
https://github.com/cschleiden/github-actions-hero/issues/10#issue-773079008

**Comment by Gothicania** [comment]
> [#10 (comment)](https://github.com/cschleiden/github-actions-hero/issues/10#issue-773079008)

**Comment by cschleiden** [comment]
Duplicate of https://github.com/cschleiden/github-actions-hero/issues/9
